import{a as h,i as y,S as L}from"./assets/vendor-Cz60lQ9U.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const w="46360280-37ac22277a0bce1d099a81efa",E="https://pixabay.com/api/";async function S(t,n=1){var o,s;try{console.log("Fetching images for query:",t,"and page:",n);const e=await h.get(E,{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:15}});return console.log("Response data:",e.data),e.data}catch(e){throw console.error("Error fetching images:",e),new Error(`Error fetching images: ${((o=e.response)==null?void 0:o.status)||""} ${((s=e.response)==null?void 0:s.statusText)||""}`)}}const q=t=>{const n=document.querySelector(".gallery");n.innerHTML=t.map(({webformatURL:o,largeImageURL:s,tags:e,likes:r,views:a,comments:g,downloads:p})=>`
            <li class="gallery-item">
                <a href="${s}" class="gallery-link">
                    <img src="${o}" alt="${e}" class="gallery-image" />
                </a>
                <div class="info">
                    <p class="info-item"><span>Likes</span> ${r}</p>
                    <p class="info-item"><span>Views</span> ${a}</p>
                    <p class="info-item"><span>Comments</span> ${g}</p>
                    <p class="info-item"><span>Downloads</span> ${p}</p>
                </div>
            </li>
        `).join("")};gallery.insertAdjacentHTML("beforeend",markup);function b(){document.querySelector(".gallery").innerHTML=""}function c(t){y.error({title:"Error",message:t})}function $(){y.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."})}function v(){document.querySelector(".loader").style.display="flex"}function M(){document.querySelector(".loader").style.display="none"}const P=document.querySelector(".search-form"),B=document.querySelector(".gallery"),d=document.querySelector(".load-more");let H=new L(".gallery a"),l=1,i="",f=0;P.addEventListener("submit",O);d.addEventListener("click",x);async function O(t){if(t.preventDefault(),i=t.target.elements.query.value.trim(),!i){c("Please enter a search query.");return}l=1,b(),u(),await m(i,l)}async function x(){l+=1,await m(i,l)}async function m(t,n){v();try{const o=await S(t,n);if(o.hits.length===0){c("Sorry, there are no images matching your search query. Please try again!"),u();return}f=o.totalHits,q(o.hits),H.refresh(),B.children.length>=f?(u(),$()):A(),I()}catch(o){c(`Error fetching images: ${o.message}`)}finally{M()}}function A(){d.style.display="block"}function u(){d.style.display="none"}function I(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
