import{a as E,i as g,S as b}from"./assets/vendor-Qob_5Ba8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&n(f)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const v="https://pixabay.com/api/",M="46360280-37ac22277a0bce1d099a81efa",m=15;async function y(t,o=1){const r=new URLSearchParams({key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:m}),n=`${v}?${r}`;try{const e=await E.get(n);return console.log("fetchImages data:",e.data),e.data}catch(e){console.error("Error fetching images:",e)}}function p(t){return t.reduce((o,r)=>o+`<article class="gallery-item">
              <a href="${r.largeImageURL}" class="gallery-link">
                  <img src="${r.webformatURL}" alt="${r.tags}" class="gallery-image" />
              </a>
              <ul class="info">
                  <li class="info-item"><strong>Likes:</strong> ${r.likes}</li>
                  <li class="info-item"><strong>Views:</strong> ${r.views}</li>
                  <li class="info-item"><strong>Comments:</strong> ${r.comments}</li>
                  <li class="info-item"><strong>Downloads:</strong> ${r.downloads}</li>
              </ul>
          </article>`,"")}function c(t){g.error({title:"Error",message:t})}function P(){g.info({title:"End of Results",message:"Sorry, but you have reached the end of search results."})}const q=document.querySelector(".search-form"),u=document.querySelector(".gallery"),d=document.querySelector(".js-load-more"),L=document.querySelector(".loader");let a=1,i=null,h=0,l=null;q.addEventListener("submit",$);d.addEventListener("click",R);async function $(t){t.preventDefault();const o=t.currentTarget;if(i=o.elements.query.value.trim(),!!i){a=1,u.innerHTML="",d.classList.add("is-hidden");try{w();const r=await y(i,a);if(h=Math.ceil(r.totalHits/m),r.totalHits===0){c("Sorry, there are no images matching your search query. Try again!");return}const n=p(r.hits);u.innerHTML=n,l?l.refresh():l=new b(".gallery a",{captionsData:"alt",captionDelay:250}),a<h&&d.classList.remove("is-hidden")}catch(r){c("Sorry, something went wrong."),console.error("Error:",r)}finally{S(),o.reset()}}}async function R(){a+=1;try{w();const t=await y(i,a),o=p(t.hits);u.insertAdjacentHTML("beforeend",o),l.refresh(),a>=h&&(d.classList.add("is-hidden"),P()),A()}catch(t){c("Sorry, something went wrong."),console.error("Error:",t)}finally{S()}}function w(){L.style.display="block"}function S(){L.style.display="none"}function A(){const t=u.lastElementChild;if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,left:0,behavior:"smooth"})}else c("Sorry, but you have reached the end of search results."),console.error("Sorry, but you have reached the end of search results.")}
//# sourceMappingURL=index.js.map
